name: CI

on:
  push:
    branches: [ main, iteration4, testing ]
  pull_request:
    branches: [ main, iteration4, testing ]

jobs:
  backend-build:
    name: backend build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: build with Gradle
      run: ./gradlew build --no-daemon

  backend-test:
    name: backend test
    runs-on: ubuntu-latest
    needs: backend-build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: JDK 21 set up
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: run tests
      run: ./gradlew test --no-daemon
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: backend-test-report
        path: build/report/test/

  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Node.js set up
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build frontend
      run: npm run build